import type {
  Asset,
  MaintenanceOrder,
  ComplianceRecord,
  Alert,
  DashboardMetrics,
  TelemetryData,
  Location,
} from '@/types';

// Locations
export const mockLocations: Location[] = [
  { id: 'loc-1', name: 'Emergency Room A', building: 'Main Hospital', floor: 1, room: '101', zone: 'ER' },
  { id: 'loc-2', name: 'ICU Bay 3', building: 'Main Hospital', floor: 2, room: '203', zone: 'ICU' },
  { id: 'loc-3', name: 'Surgery Suite 1', building: 'Surgical Wing', floor: 3, room: '301', zone: 'OR' },
  { id: 'loc-4', name: 'Radiology Lab', building: 'Diagnostic Center', floor: 1, room: '110', zone: 'RAD' },
  { id: 'loc-5', name: 'Cardiology Unit', building: 'Main Hospital', floor: 4, room: '401', zone: 'CARD' },
  { id: 'loc-6', name: 'Laboratory', building: 'Diagnostic Center', floor: 2, room: '220', zone: 'LAB' },
  { id: 'loc-7', name: 'Pharmacy Storage', building: 'Main Hospital', floor: 1, room: '115', zone: 'PHARM' },
  { id: 'loc-8', name: 'Physical Therapy', building: 'Rehabilitation Wing', floor: 1, room: '105', zone: 'PT' },
];

// Assets
export const mockAssets: Asset[] = [
  {
    id: 'ast-001',
    name: 'Philips IntelliVue MX800',
    serialNumber: 'PH-MX800-2023-001',
    manufacturer: 'Philips Healthcare',
    model: 'IntelliVue MX800',
    category: 'monitoring',
    status: 'operational',
    riskLevel: 'high',
    location: mockLocations[1],
    purchaseDate: '2023-01-15',
    warrantyExpiry: '2026-01-15',
    lastMaintenance: '2024-10-01',
    nextMaintenance: '2025-01-01',
    utilizationRate: 87,
    healthScore: 94,
    tags: ['critical-care', 'monitoring', 'icu'],
    assignedDepartment: 'Intensive Care Unit',
    createdAt: '2023-01-15T10:00:00Z',
    updatedAt: '2024-11-20T14:30:00Z',
  },
  {
    id: 'ast-002',
    name: 'GE Discovery CT750 HD',
    serialNumber: 'GE-CT750-2022-042',
    manufacturer: 'GE Healthcare',
    model: 'Discovery CT750 HD',
    category: 'diagnostic',
    status: 'operational',
    riskLevel: 'critical',
    location: mockLocations[3],
    purchaseDate: '2022-06-20',
    warrantyExpiry: '2025-06-20',
    lastMaintenance: '2024-09-15',
    nextMaintenance: '2024-12-15',
    utilizationRate: 92,
    healthScore: 88,
    tags: ['imaging', 'ct-scan', 'radiology'],
    assignedDepartment: 'Radiology',
    createdAt: '2022-06-20T10:00:00Z',
    updatedAt: '2024-11-18T09:15:00Z',
  },
  {
    id: 'ast-003',
    name: 'Medtronic HeartWare HVAD',
    serialNumber: 'MD-HVAD-2024-007',
    manufacturer: 'Medtronic',
    model: 'HeartWare HVAD System',
    category: 'therapeutic',
    status: 'maintenance',
    riskLevel: 'critical',
    location: mockLocations[4],
    purchaseDate: '2024-02-10',
    warrantyExpiry: '2027-02-10',
    lastMaintenance: '2024-08-20',
    nextMaintenance: '2024-11-20',
    utilizationRate: 45,
    healthScore: 76,
    tags: ['cardiac', 'life-support', 'ventricular-assist'],
    assignedDepartment: 'Cardiology',
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-11-19T16:45:00Z',
  },
  {
    id: 'ast-004',
    name: 'Stryker System 8 Power Tools',
    serialNumber: 'ST-SYS8-2023-089',
    manufacturer: 'Stryker',
    model: 'System 8',
    category: 'surgical',
    status: 'operational',
    riskLevel: 'high',
    location: mockLocations[2],
    purchaseDate: '2023-04-05',
    warrantyExpiry: '2026-04-05',
    lastMaintenance: '2024-10-30',
    nextMaintenance: '2025-01-30',
    utilizationRate: 68,
    healthScore: 91,
    tags: ['surgical', 'orthopedic', 'power-tools'],
    assignedDepartment: 'Surgery',
    createdAt: '2023-04-05T10:00:00Z',
    updatedAt: '2024-11-15T11:20:00Z',
  },
  {
    id: 'ast-005',
    name: 'Siemens MAGNETOM Vida',
    serialNumber: 'SI-VIDA-2023-015',
    manufacturer: 'Siemens Healthineers',
    model: 'MAGNETOM Vida 3T',
    category: 'diagnostic',
    status: 'critical',
    riskLevel: 'critical',
    location: mockLocations[3],
    purchaseDate: '2023-08-12',
    warrantyExpiry: '2026-08-12',
    lastMaintenance: '2024-07-01',
    nextMaintenance: '2024-10-01',
    utilizationRate: 78,
    healthScore: 62,
    tags: ['imaging', 'mri', 'radiology'],
    assignedDepartment: 'Radiology',
    createdAt: '2023-08-12T10:00:00Z',
    updatedAt: '2024-11-20T08:00:00Z',
  },
  {
    id: 'ast-006',
    name: 'Draeger Evita V500',
    serialNumber: 'DR-V500-2024-023',
    manufacturer: 'Dräger',
    model: 'Evita V500',
    category: 'therapeutic',
    status: 'operational',
    riskLevel: 'high',
    location: mockLocations[1],
    purchaseDate: '2024-01-20',
    warrantyExpiry: '2027-01-20',
    lastMaintenance: '2024-10-15',
    nextMaintenance: '2025-01-15',
    utilizationRate: 95,
    healthScore: 97,
    tags: ['ventilator', 'icu', 'respiratory'],
    assignedDepartment: 'Intensive Care Unit',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-11-19T10:30:00Z',
  },
  {
    id: 'ast-007',
    name: 'Roche Cobas 8000',
    serialNumber: 'RC-8000-2022-056',
    manufacturer: 'Roche Diagnostics',
    model: 'Cobas 8000 Modular Analyzer',
    category: 'laboratory',
    status: 'operational',
    riskLevel: 'medium',
    location: mockLocations[5],
    purchaseDate: '2022-11-08',
    warrantyExpiry: '2025-11-08',
    lastMaintenance: '2024-09-01',
    nextMaintenance: '2024-12-01',
    utilizationRate: 88,
    healthScore: 85,
    tags: ['laboratory', 'analyzer', 'blood-chemistry'],
    assignedDepartment: 'Laboratory',
    createdAt: '2022-11-08T10:00:00Z',
    updatedAt: '2024-11-17T14:00:00Z',
  },
  {
    id: 'ast-008',
    name: 'Hill-Rom P500 Bed',
    serialNumber: 'HR-P500-2023-112',
    manufacturer: 'Hill-Rom',
    model: 'Progressa P500',
    category: 'support',
    status: 'operational',
    riskLevel: 'low',
    location: mockLocations[0],
    purchaseDate: '2023-03-15',
    warrantyExpiry: '2028-03-15',
    lastMaintenance: '2024-11-01',
    nextMaintenance: '2025-02-01',
    utilizationRate: 72,
    healthScore: 93,
    tags: ['bed', 'patient-care', 'emergency'],
    assignedDepartment: 'Emergency',
    createdAt: '2023-03-15T10:00:00Z',
    updatedAt: '2024-11-18T13:45:00Z',
  },
];

// Maintenance Orders
export const mockMaintenanceOrders: MaintenanceOrder[] = [
  {
    id: 'wo-001',
    assetId: 'ast-005',
    asset: mockAssets[4],
    title: 'MRI Magnet Calibration',
    description: 'Scheduled annual magnet calibration and shimming procedure. Field homogeneity check required.',
    type: 'preventive',
    priority: 'urgent',
    status: 'in_progress',
    assignedTo: 'Dr. Michael Chen',
    scheduledDate: '2024-11-20',
    estimatedDuration: 480,
    notes: 'Patient schedules cleared for 2 days. Siemens engineer on-site.',
    createdAt: '2024-11-15T10:00:00Z',
    updatedAt: '2024-11-20T08:00:00Z',
  },
  {
    id: 'wo-002',
    assetId: 'ast-003',
    asset: mockAssets[2],
    title: 'HVAD Controller Firmware Update',
    description: 'Critical firmware update to address reported communication issues.',
    type: 'corrective',
    priority: 'high',
    status: 'scheduled',
    assignedTo: 'Sarah Johnson',
    scheduledDate: '2024-11-22',
    estimatedDuration: 120,
    createdAt: '2024-11-18T14:00:00Z',
    updatedAt: '2024-11-18T14:00:00Z',
  },
  {
    id: 'wo-003',
    assetId: 'ast-002',
    asset: mockAssets[1],
    title: 'CT Scanner Tube Replacement',
    description: 'Scheduled X-ray tube replacement based on predictive maintenance alerts.',
    type: 'predictive',
    priority: 'medium',
    status: 'scheduled',
    assignedTo: 'James Williams',
    scheduledDate: '2024-12-01',
    estimatedDuration: 360,
    parts: [
      { id: 'prt-001', name: 'X-Ray Tube Assembly', partNumber: 'GE-XRT-750', quantity: 1, cost: 45000 },
      { id: 'prt-002', name: 'Cooling System Filter', partNumber: 'GE-CSF-200', quantity: 2, cost: 250 },
    ],
    createdAt: '2024-11-10T09:00:00Z',
    updatedAt: '2024-11-15T11:30:00Z',
  },
  {
    id: 'wo-004',
    assetId: 'ast-007',
    asset: mockAssets[6],
    title: 'Analyzer Reagent System Cleaning',
    description: 'Quarterly deep cleaning and recalibration of reagent dispensing system.',
    type: 'preventive',
    priority: 'low',
    status: 'completed',
    assignedTo: 'Emily Rodriguez',
    scheduledDate: '2024-11-15',
    completedDate: '2024-11-15',
    estimatedDuration: 180,
    actualDuration: 165,
    createdAt: '2024-11-01T10:00:00Z',
    updatedAt: '2024-11-15T16:00:00Z',
  },
  {
    id: 'wo-005',
    assetId: 'ast-006',
    asset: mockAssets[5],
    title: 'Ventilator Flow Sensor Replacement',
    description: 'Preventive replacement of flow sensors due to high utilization hours.',
    type: 'preventive',
    priority: 'medium',
    status: 'scheduled',
    assignedTo: 'Dr. Michael Chen',
    scheduledDate: '2024-11-25',
    estimatedDuration: 90,
    parts: [
      { id: 'prt-003', name: 'Flow Sensor Kit', partNumber: 'DR-FSK-V500', quantity: 1, cost: 1200 },
    ],
    createdAt: '2024-11-12T08:00:00Z',
    updatedAt: '2024-11-12T08:00:00Z',
  },
];

// Compliance Records
export const mockComplianceRecords: ComplianceRecord[] = [
  {
    id: 'cmp-001',
    assetId: 'ast-002',
    asset: mockAssets[1],
    standard: 'FDA 21 CFR Part 820',
    requirement: 'Quality System Regulation',
    status: 'compliant',
    lastAudit: '2024-09-15',
    nextAudit: '2025-03-15',
  },
  {
    id: 'cmp-002',
    assetId: 'ast-005',
    asset: mockAssets[4],
    standard: 'IEC 60601-2-33',
    requirement: 'MRI Safety Requirements',
    status: 'pending_review',
    lastAudit: '2024-06-01',
    nextAudit: '2024-12-01',
    notes: 'Awaiting updated safety documentation post-calibration',
  },
  {
    id: 'cmp-003',
    assetId: 'ast-003',
    asset: mockAssets[2],
    standard: 'ISO 13485:2016',
    requirement: 'Medical Device QMS',
    status: 'compliant',
    lastAudit: '2024-08-20',
    nextAudit: '2025-02-20',
  },
  {
    id: 'cmp-004',
    assetId: 'ast-001',
    asset: mockAssets[0],
    standard: 'IEC 60601-1',
    requirement: 'Medical Electrical Equipment Safety',
    status: 'compliant',
    lastAudit: '2024-10-01',
    nextAudit: '2025-04-01',
  },
];

// Alerts
export const mockAlerts: Alert[] = [
  {
    id: 'alt-001',
    type: 'critical',
    title: 'MRI System Fault Detected',
    message: 'MAGNETOM Vida reporting helium level warning. Immediate inspection required.',
    assetId: 'ast-005',
    asset: mockAssets[4],
    timestamp: '2024-11-20T07:45:00Z',
    acknowledged: false,
  },
  {
    id: 'alt-002',
    type: 'warning',
    title: 'Maintenance Overdue',
    message: 'HeartWare HVAD scheduled maintenance is 5 days overdue.',
    assetId: 'ast-003',
    asset: mockAssets[2],
    timestamp: '2024-11-20T06:00:00Z',
    acknowledged: false,
  },
  {
    id: 'alt-003',
    type: 'warning',
    title: 'Low Utilization Alert',
    message: 'CT Scanner utilization dropped below threshold in the last 7 days.',
    assetId: 'ast-002',
    asset: mockAssets[1],
    timestamp: '2024-11-19T14:30:00Z',
    acknowledged: true,
    acknowledgedBy: 'Sarah Johnson',
    acknowledgedAt: '2024-11-19T15:00:00Z',
  },
  {
    id: 'alt-004',
    type: 'info',
    title: 'Warranty Expiring Soon',
    message: 'Discovery CT750 HD warranty expires in 7 months. Consider renewal.',
    assetId: 'ast-002',
    asset: mockAssets[1],
    timestamp: '2024-11-18T09:00:00Z',
    acknowledged: true,
    acknowledgedBy: 'James Williams',
    acknowledgedAt: '2024-11-18T10:30:00Z',
  },
];

// Dashboard Metrics
export const mockDashboardMetrics: DashboardMetrics = {
  totalAssets: 847,
  assetsChange: 12,
  operationalAssets: 782,
  operationalChange: 3.2,
  maintenanceDue: 23,
  maintenanceChange: -8,
  complianceRate: 94.7,
  complianceChange: 1.3,
  averageUtilization: 78.4,
  utilizationChange: 2.1,
  criticalAlerts: 3,
  alertsChange: -2,
};

// Telemetry data for real-time tracking
export const generateTelemetryData = (): TelemetryData[] => {
  return mockAssets.map((asset, index) => ({
    assetId: asset.id,
    timestamp: new Date().toISOString(),
    location: {
      x: 100 + (index * 80) % 400,
      y: 100 + Math.floor(index / 5) * 100,
      floor: asset.location.floor,
      zone: asset.location.zone,
    },
    battery: 60 + Math.random() * 40,
    signalStrength: -40 - Math.random() * 30,
    temperature: 20 + Math.random() * 5,
    motion: Math.random() > 0.7,
  }));
};

// Chart data generators
export const generateUtilizationTrend = () => {
  const data = [];
  for (let i = 30; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    data.push({
      date: date.toISOString().split('T')[0],
      value: 70 + Math.random() * 20,
    });
  }
  return data;
};

export const generateMaintenanceByCategory = () => [
  { category: 'Preventive', value: 45 },
  { category: 'Corrective', value: 28 },
  { category: 'Predictive', value: 18 },
  { category: 'Emergency', value: 9 },
];

export const generateAssetsByStatus = () => [
  { status: 'Operational', value: 782, color: '#22c55e' },
  { status: 'Maintenance', value: 38, color: '#f59e0b' },
  { status: 'Critical', value: 12, color: '#ef4444' },
  { status: 'Offline', value: 15, color: '#6b7280' },
];

export const generateDepartmentAssets = () => [
  { department: 'ICU', assets: 124, utilization: 92 },
  { department: 'Radiology', assets: 89, utilization: 85 },
  { department: 'Surgery', assets: 156, utilization: 78 },
  { department: 'Emergency', assets: 98, utilization: 88 },
  { department: 'Laboratory', assets: 112, utilization: 72 },
  { department: 'Cardiology', assets: 67, utilization: 81 },
];
